services:
  app:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
      target: dev
    container_name: templa-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ../../:/app
      - /app/node_modules
    command: npm run dev:docker
    networks:
      - templa-network

networks:
  templa-network:
    driver: bridge
